variables:
  NODE_VERSION: "10"
  PHP_VERSION: "7.4"

cache: {}

stages:
  - cs
  - test
  - functional_test
  - release

js-cs:
  image: registry.gitlab.com/dedi-agency/interne/docker-images/node:${NODE_VERSION}
  stage: cs
  script:
    - make front-test-cs ENV=ci
  except:
    - tags

php-cs:
  image: registry.gitlab.com/dedi-agency/interne/docker-images/php:${PHP_VERSION}
  variables:
    PHP_MEMORY_LIMIT: 4G
  stage: cs
  script:
    - make back-test-cs ENV=ci
  except:
    - tags

php-test-spec:
  image: registry.gitlab.com/dedi-agency/interne/docker-images/php:${PHP_VERSION}
  variables:
    PHP_MEMORY_LIMIT: 4G
  stage: test
  script:
    - make test-spec ENV=ci
  except:
    - tags

functional_test:
  image: registry.gitlab.com/dedi-agency/interne/docker-images/php:${PHP_VERSION}
  variables:
    PHP_MEMORY_LIMIT: 4G
    APP_ENV: test
    DATABASE_URL: sqlite:///${CI_PROJECT_DIR}/etc/db.sqlite
  stage: functional_test
  script:
    - sudo apk add --upgrade sqlite php7-sqlite3 php7-pdo_sqlite
    - composer install --no-scripts
    - cd tests/Application
    - php bin/console doctrine:database:create --no-interaction
    - php bin/console doctrine:schema:update --force --no-interaction
    - php bin/console sylius:fixtures:load --no-interaction
    - cd ../..
    - php vendor/bin/behat --tags @seo
  except:
    - tags

semantic_release:
  stage: release
  image: node:10
  variables:
    GITLAB_TOKEN: $ACCESS_TOKEN
  script:
    - npm install @semantic-release/{git,commit-analyzer,release-notes-generator,changelog,gitlab,gitlab-config}
    - npx semantic-release -e @semantic-release/gitlab-config
  only:
    refs:
      - master
