publish: ['@semantic-release/gitlab']
verifyConditions: ['@semantic-release/gitlab']
generateNotes: ['@semantic-release/release-notes-generator']
branches:
    - "master"
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - - "@semantic-release/npm"
      - npmPublish: false
    - "@semantic-release/changelog"
    - - "@semantic-release/git"
      - assets:
            - CHANGELOG.md
        message: "chore(release): Release ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
