version: '3.4'

services:
    php-cli:
        user: ${UID}
        image: php:7.4-fpm-alpine
        volumes:
            - .:/src
        working_dir: /src

    composer:
        image: registry.gitlab.com/dedi-agency/interne/docker-images/php:sylius-plugin
        environment:
            - USER_ID=${UID:-1001}
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - .:/var/app:rw,cached
        working_dir: /var/app
        command: ["composer", "install"]

    php:
        image: registry.gitlab.com/dedi-agency/interne/docker-images/php:7.4
        depends_on:
            - composer
        environment:
            - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
            - APP_ENV=${ENV:-dev}
            - APP_DEBUG=${DEBUG:-1}
            - USER_ID=${UID:-1001}
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - .:/var/app:rw,cached
        ports:
            - ${DOCKER_PHP_PORT:-9000}:9000
        working_dir: /var/app/tests/Application
        command: ["php", "-S", "0.0.0.0:9000", "-t", "public"]

    mysql:
        image: percona:5.7
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - sql-mode=STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_ENGINE_SUBSTITUTION
        ports:
            - ${DOCKER_MYSQL_PORT:-3306}:3306

    node:
        image: registry.gitlab.com/dedi-agency/interne/docker-images/node:latest
        environment:
            - USER_ID=${UID:-1001}
        volumes:
            - .:/var/app:rw,cached
        working_dir: /var/app/tests/Application
        command: ["npm", "install"]
